name: PR Validation on UAT

on:
  pull_request:
    branches: [staging]
    paths: ['force-app/**']

jobs:
  validate:
    uses: bes-innovation/gmd-seed-gh-workflow/.github/workflows/gmd-seed-sf-validate-wfl.yml@v1
    with:
      environment: uat
      target-org: uat
      severity-threshold: "5"
    secrets: inherit
